# Definição do Schema para a planilha de Clientes
clientes:
  aba: "Sheet1"
  colunas:
    cliente_id: "int64"
    nome_cliente: "object"
    email: "object"
    status_cliente: "category"
    cidade: "object"
    estado: "object"
  colunas_data:
    - data_cadastro
    - data_desativacao